title: Adhuri Dastaan
author: vivek1609
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I created this website in the initial phase of my learning github. well i'm very excited while doing this project. hope to learn a lot from here.thnx for reading.

# social links
twitter_username: vivekmunda1609
github_username:  vivekmunda

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
